import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next App Typescript Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <nav className="p-4 text-lg font-light">
        <Link href="/about">
          About
        </Link>
      </nav>

      <main className="p-8 text-center">
        <h1 className="text-4xl font-bold">Home Page</h1>
      </main>

      <footer className="p-4">
        <p className="text-lg font-light">Footer</p>
      </footer>
    </div>
  )
}

export default Home